# azure-pipeline.yml
# This pipeline runs Playwright tests in parallel using Azure DevOps.

trigger:
- main  # or your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  displayName: "Install dependencies"
  inputs:
    targetType: 'inline'
    script: 'npm ci'
    workingDirectory: 'tests/' # update accordingly

- task: AzureCLI@2
  displayName: "Run Playwright Test"
  env:
    PLAYWRIGHT_SERVICE_URL: $(PLAYWRIGHT_SERVICE_URL)
    # PLAYWRIGHT_SERVICE_ACCESS_TOKEN: $(PLAYWRIGHT_SERVICE_ACCESS_TOKEN) # Not recommended, use Microsoft Entra ID authentication.
  inputs:
    azureSubscription: 'playwrighttestts' # Service connection for Azure authentication
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      npx playwright test ClientAppPO.spec.js -c playwright.service.config.ts
    addSpnToEnvironment: true

- task: PublishPipelineArtifact@1
  displayName: "Upload Playwright report"
  inputs:
    targetPath: 'tests/playwright-report/' # update accordingly
    artifact: 'Playwright tests'
    publishLocation: 'pipeline'
